-- MySQL Script generated by MySQL Workbench
-- Tue Oct 13 12:39:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema assignment4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assignment4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assignment4` DEFAULT CHARACTER SET utf8 ;
USE `assignment4` ;

-- -----------------------------------------------------
-- Table `assignment4`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment4`.`region` (
  `r_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NULL,
  PRIMARY KEY (`r_id`))
ENGINE = InnoDB;
ALTER TABLE region AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `assignment4`.`blood_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment4`.`blood_group` (
  `b_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(5) NULL,
  PRIMARY KEY (`b_id`))
ENGINE = InnoDB;
ALTER TABLE blood_group AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `assignment4`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment4`.`users` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(25) NULL,
  `lname` VARCHAR(25) NULL,
  `dob` DATE NULL,
  `r_id` INT NULL,
  `b_id` INT NULL,
  `phone` VARCHAR(10) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(25) NULL,
  PRIMARY KEY (`u_id`),
  CONSTRAINT `r_id`
    FOREIGN KEY (`r_id`)
    REFERENCES `assignment4`.`region` (`r_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `b_id`
    FOREIGN KEY (`b_id`)
    REFERENCES `assignment4`.`blood_group` (`b_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
ALTER TABLE users AUTO_INCREMENT = 1001;

-- -----------------------------------------------------
-- Table `assignment4`.`donations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment4`.`donations` (
  `d_id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NULL,
  `d_date` DATE NULL,
  PRIMARY KEY (`d_id`),
  CONSTRAINT `u_id`
    FOREIGN KEY (`u_id`)
    REFERENCES `assignment4`.`users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
ALTER TABLE donations AUTO_INCREMENT = 1;

-- =======================================================================================================================================================================
-- 										DATA EXERCISES
-- =======================================================================================================================================================================
-- 1. Add data to all table's.

-- 1.1 Region table data
INSERT INTO region (name) VALUES ("North"), ("Middle") , ("South");
SELECT * FROM region;

-- 1.2 Blood group table data
INSERT INTO blood_group (type) VALUES ("A+ve"), ("A-ve"), ("B+ve"), ("B-ve"), ("O+ve"), ("O-ve"), ("AB+ve"), ("AB-ve");
SELECT * FROM blood_group;

-- 1.3 User table data
INSERT INTO users (fname, lname, dob, r_id, b_id, phone, email, password) VALUES
("Ananya", "Vinod", "1999-10-13", 3, 3, "6234567890", "ananya@qburst.com", "ananya@123"), -- 1001
("Ann", "Susan", "1998-08-10", 2, 3, "9234557890", "anns@qburst.com", "ann@123"),
("Haripriya", "Jagannathan", "1999-09-17", 3, 5, "6238957968", "haripriya@qburst.com", "haripriya@123"),
("Nikhil", "Anil Kumar", "1998-05-23", 2, 1, "8234560890", "nikhilanilkumar@qburst.com", "nikhil@123"),
("Sidharth", "Sujithlal", "1998-10-23", 2, 1, "7234067890", "sidharths@qburst.com", "sidharth@123"),
("Thejus", "Satheesan", "1997-02-13", 1, 7, "6642567890", "thejuss@qburst.com", "thejus@123");
SELECT * FROM users;

-- 1.4 Donation table data
INSERT INTO donations (u_id, d_date) VALUES
(1006, "2020-02-12"),
(1004, "2020-05-16"),
(1006, "2020-06-12"),
(1001, "2020-10-05"),
(1005, "2020-10-05");
SELECT * FROM donations;

-- 2. Check whether a user registered with blood Group B+ve and first name as ‘Bruce’
SELECT EXISTS (SELECT * FROM users AS u
LEFT JOIN blood_group as b ON u.b_id = b.b_id
WHERE u.fname="Bruce" AND b.type="B+ve") AS Status; -- Status = 0: User does not exist

-- 3. Show the first_name, last_name, contact no of all users with bloog_group 'B+ve';
SELECT u.fname, u.lname, u.phone FROM users AS u
LEFT JOIN blood_group AS b ON u.b_id = b.b_id
WHERE b.type="B+ve";

-- 4. Fetch first name, last name and contact no of all users with blood group 'A+ve' and located in the 'middle' region.
SELECT u.fname, u.lname, u.phone FROM users AS u
LEFT JOIN blood_group AS b ON u.b_id = b.b_id
LEFT JOIN region AS r ON u.r_id = r.r_id
WHERE b.type="A+ve" AND r.name="Middle";

-- 5. Fetch details of all transaction in one particular day
SELECT d.d_id AS Donation_id, u.fname AS First_name, u.lname AS Last_name, u.phone AS Phone_number
FROM donations AS d 
RIGHT JOIN users AS u ON d.u_id = u.u_id 
WHERE d.d_date = "2020-10-05";

-- 6. Update contact no of a user to '987698765' whose user id is 1001
UPDATE users SET phone = '987698765' WHERE u_id = 1001;

-- 7. Edit last_name of a user to 'speedster' whose id is 1002
UPDATE users SET lname = 'speedster' WHERE u_id = 1002;

-- 8. Remove a user whose id is 1002 from our blood bank
DELETE FROM users WHERE u_id = 1002;

-- 9. Find the count of donors in each regions
SELECT r.name AS Region_name, COUNT(*) AS Donor_count FROM users AS u
LEFT JOIN region AS r ON u.r_id = r.r_id
GROUP BY r.name;

-- 10. List out all users (first name,last name) based on their age from old to young
SELECT * FROM users AS u ORDER BY u.dob;