-- MySQL Script generated by MySQL Workbench
-- Tue Oct 13 12:39:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema assignment4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assignment4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assignment4` DEFAULT CHARACTER SET utf8 ;
USE `assignment4` ;

-- -----------------------------------------------------
-- Table `assignment4`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment4`.`region` (
  `r_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NULL,
  PRIMARY KEY (`r_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assignment4`.`blood_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment4`.`blood_group` (
  `b_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(5) NULL,
  PRIMARY KEY (`b_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assignment4`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment4`.`users` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(25) NULL,
  `lname` VARCHAR(25) NULL,
  `dob` DATE NULL,
  `r_id` INT NULL,
  `b_id` INT NULL,
  `phone` VARCHAR(10) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(25) NULL,
  PRIMARY KEY (`u_id`),
  CONSTRAINT `r_id`
    FOREIGN KEY (`r_id`)
    REFERENCES `assignment4`.`region` (`r_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `b_id`
    FOREIGN KEY (`b_id`)
    REFERENCES `assignment4`.`blood_group` (`b_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assignment4`.`donations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment4`.`donations` (
  `d_id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NULL,
  `d_date` DATE NULL,
  PRIMARY KEY (`d_id`),
  CONSTRAINT `u_id`
    FOREIGN KEY (`u_id`)
    REFERENCES `assignment4`.`users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- =======================================================================================================================================================================
-- 										DATA EXERCISES
-- =======================================================================================================================================================================
