-- MySQL Script generated by MySQL Workbench
-- Mon Oct 12 14:28:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema assignment3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assignment3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assignment3` DEFAULT CHARACTER SET utf8 ;
USE `assignment3` ;

-- -----------------------------------------------------
-- Table `assignment3`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment3`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;
ALTER TABLE roles AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `assignment3`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment3`.`employee` (
  `emp_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NULL,
  `role_id` INT NULL,
  PRIMARY KEY (`emp_id`),
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `assignment3`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
ALTER TABLE employee AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `assignment3`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment3`.`skills` (
  `skill_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(15) NULL,
  `name` VARCHAR(25) NULL,
  PRIMARY KEY (`skill_id`))
ENGINE = InnoDB;
ALTER TABLE skills AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `assignment3`.`employee_skill_mapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment3`.`employee_skill_mapping` (
  `emp_id` INT NULL,
  `skill_id` INT NULL,
  CONSTRAINT `emp_id`
    FOREIGN KEY (`emp_id`)
    REFERENCES `assignment3`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `skill_id`
    FOREIGN KEY (`skill_id`)
    REFERENCES `assignment3`.`skills` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assignment3`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment3`.`projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `owner` INT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;
ALTER TABLE projects AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `assignment3`.`employee_project_mapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment3`.`employee_project_mapping` (
  `emp_id` INT NULL,
  `project_id` INT NULL,
  CONSTRAINT `emp_idd`
    FOREIGN KEY (`emp_id`)
    REFERENCES `assignment3`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_idd`
    FOREIGN KEY (`project_id`)
    REFERENCES `assignment3`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

